### ISSUE TITLE
Raised fist

### ISSUE THREAD

**Issue by tcrowe** [hyperboria/logos#3]
https://github.com/hyperboria/logos/blob/master/berlinmeshnet.png
https://infogalactic.com/info/Raised_fist

Raised fist logo is used in a lot of Communist advertising. The death toll of Communism is over 100 million. Isn't this insensitive to the Chinese and Russians who perished en masse in a holocaust worse than even Hitler would do?

**Comment by ansuz** [comment]
:+1: for jumping immediately to a hitler comparison.

**Comment by wfleurant** [comment]
There's a common understanding of Soviet Communism having won the war on Nazism... The logo lacks an any associations to the polity found in this issue.

**Comment by tcrowe** [comment]
I assumed you'd try to justify it. I'd just like to remind people WWII is over and those ideologies they had were unbelievably destructive. It's WWIII now so maybe you'll find a way to move on from all that crusty old Communism that The Chosen gave you.

**Comment by ansuz** [comment]
You must be real fun at parties @tcrowe

**Comment by tcrowe** [comment]
Soviet genocide of the Kazak steppe nomad people
https://www.youtube.com/watch?v=JNGHagc5tQ8

`Soviet Communism having won the war` at what cost?

@ansuz @wfleurant

**Comment by ansuz** [comment]
I haven't laughed this hard in a while. If you're ever in Paris look me up and I'll buy you a beer.
